logging:
  backup_count: 10
  level: INFO
  max_size_mb: 10
  path: /var/log/pingit
  retention_days: 7
ping:
  interval: 1
reporting:
  interval: 10
targets:
- host: isr-fullvpn.amdocs.com
  name: Amdocs Isarel VPN
  timeout: 0.5
- host: 10.10.0.44
  name: Device at home
  timeout: 0.5
- host: 10.10.0.138
  name: Home gateway
  timeout: 0.5
- host: 8.8.8.8
  name: Google DNS
  timeout: 0.5
webserver_config: /etc/pingit/webserver-config.yaml  # Ignored in test mode, uses ./webserver-config.yaml instead
